- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/drone/imu"
  gz_topic_name: "/world/drone_world/model/drone/link/imu_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/drone/motor_speed"
  gz_topic_name: "/model/drone/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ

- ros_topic_name: "/drone/pose"
  gz_topic_name: "/model/drone/pose"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
